### ISSUE TITLE
Meta boxes / conditions visibility issues in WP 6.2

### ISSUE THREAD

**Issue by ChipRyan** [htmlburger/carbon-fields#1157]
## Version

  - Carbon Fields: 3.5.3
  - WordPress: 6.2
  - PHP: 8.0

## Expected Behavior
Show meta box according to condition types

## Actual Behavior
Meta box not displayed

## Container definition
```php
Container::make( 'post_meta', __( 'Page Components' ) )
	->where( 'post_type', '=', 'page' )
	->where( 'post_template', '=', 'templates/homepage.php' )
	->add_fields( array(
                Field::make('text', 'text', 'Test')
        ) );
```

## Comments
Seems there is a problem with the meta box visibility when certain condition types are used. The above definition does not load the meta box properly anymore after upgrading to the latest WP 6.2. If I remove the post_template condition and only leave the post_type one, it works properly but that means that the container is not restricted to the template anymore and it's going to be displayed on all pages.

The conditions and container worked fine in the previous 6.1.1. It's only happening on WP 6.2. Tested on a fresh installation with no other installed plugins.

A few hints that may help. The meta box should be displayed. When toggling the panel from Preferences, WP toggles the 'is-hidden' class on the panel:
![image](https://user-images.githubusercontent.com/24570809/228811266-85afe8a5-250a-4d7d-b6c0-0a2f99583607.png)

![image](https://user-images.githubusercontent.com/24570809/228811774-4e1111e1-1636-4388-bbb4-2ac2bd2d0f30.png)

When the panel is enabled from Preferences, there is no 'is-hidden' class applied to it, yet there is a 'hidden' attribute still present:
![image](https://user-images.githubusercontent.com/24570809/228811994-87bfd3ee-462a-4eff-8b1e-584475690ad8.png)

I don't know how Carbon Fields handles the visibility but it seems that the hidden attribute is from CF, not WordPress.

**Comment by tvmb** [comment]
We are experiencing the same issue, in particular with both the `->where('post_template')` and `show_on_template` filters

**Comment by ipravdorub** [comment]
As a temporary measure, you can add styling to the admin panel. Example:

` add_action( 'admin_head', 'add_admin_style' );
    function add_admin_style() {
      echo '<style>.edit-post-meta-boxes-area .postbox.carbon-box {display: block;}</style>';
    } 
`

**Comment by r61boff** [comment]
Try to replace
`->where( 'post_template', '=', 'templates/homepage.php' )`
with
`->where( 'post_id', 'CUSTOM', function($post_id) {
        return ( get_page_template_slug ( $post_id ) == 'templates/homepage.php' );
    } )`
In my case editor brokes then used `->where( 'post_template', '=', 'templates/homepage.php' )`

**Comment by PolluxDevelopersTeam** [comment]
Rolling back wordpress to version 6.1.1 solved the problem

**Comment by HTMLBurger-NG** [comment]
Hi @ChipRyan,

Thank you for your feedback.
We've recently pushed a new release v3.6.0 where we've fixed the issues with WordPress 6.2.

**Comment by broiniac** [comment]
Issue is still here. WP v6.3.1, Carbon v3.6.0.
For anyone in hurry - @r61boff workarkound is working. Use custom condition instead of build-in `post_type` one.
