### ISSUE TITLE
Compatibility issue with php 8.3.1

### ISSUE THREAD

**Issue by rstrah** [htmlburger/carbon-fields#1217]
## Version

  3.6.3 - Carbon Fields:
 6.4.3 - WordPress:
  8.3.1 - PHP:

## Expected Behavior
No errors like "Calling get_class() without arguments is deprecated"

## Actual Behavior
https://prnt.sc/5qPRcRUFP_py

**Comment by alvarosego01** [comment]
Hello.

I have the same problem, I solved it by downgrading php to 8.1

**Comment by chrismccoy** [comment]
> Hello.
> 
> I have the same problem, I solved it by downgrading php to 8.1

carbon works with php 8.2, the get_class() needs to be replaced with static::class in 7 diff files. if you really want to use php 8.3

**Comment by atanas-vasilev-dev** [comment]
This was fixed in https://github.com/htmlburger/carbon-fields/pull/1239 and will be added to the next release.

**Comment by atanas-vasilev-dev** [comment]
The fix for this issue is now released in https://github.com/htmlburger/carbon-fields/releases/tag/v3.6.5

**Comment by gursuj** [comment]
Still getting this on v3.6.5

`Deprecated: Calling get_class() without arguments is deprecated in /home/sujal/Local Sites/thp-new/app/public/wp-content/plugins/carbon-fields/core/Libraries/Plugin_Update_Warning/Plugin_Update_Warning.php on line 12`

**Comment by chrismccoy** [comment]
update your carbon to 3.6.9

**Comment by gursuj** [comment]
Thanks. I did see github had a newer version yesterday but didn't get time to try it. Works fine now with composer.

I was using the pre-built non-composer versions linked in [this section of the docs](https://docs.carbonfields.net/plugin-quickstart.html#without-composer) and seems the [latest link](https://carbonfields.net/zip/latest/) provides v3.6.4 and the [release archive](https://carbonfields.net/release-archive/) has upto 3.6.5. Maybe those should be updated?
