### ISSUE TITLE
Complex Fields not saved on falsy field values

### ISSUE THREAD

**Issue by georgknabl** [htmlburger/carbon-fields#47]
When adding complex fields and not giving their subfields any input the whole complex field item is missing after saving. This also occurs when the only input field in the group is a checkbox that is not ticked (i.e. is falsy).

Why would you need empty complex fields anyway, you might ask? Well, we use complex fields as modules (previously in ACF we used flexible content fields) and some modules do not have any data. Example: a divider module that just renders a line and doesn't need data attached. Of course you can solve it via dummy values but that just doesn't seem right.

**Comment by m1r0** [comment]
Hi @georgknabl,

Your suggestion makes sense, we will implement it in the next release. Thanks!

**Comment by georgknabl** [comment]
Great, thanks!

**Comment by m1r0** [comment]
The issue has been fixed (https://github.com/htmlburger/carbon-fields/commit/c69bdebdd57cf1e73871dba4e94a513eb2e216d7).

**Comment by georgknabl** [comment]
Unfortunately this still occurs if complex fields are saved that do not contain any fields.

**Test Case:**
When trying to add this field and saving it, it is vanished afterwards.

```
<?php
use Carbon_Fields\Container;
use Carbon_Fields\Field;

Container::make('post_meta', 'Empty Fields Test')
    ->show_on_post_type('page')
    ->add_fields(array(
        Field::make('complex', 'fields', 'Fields')
            ->add_fields('module', 'Empty Field', array(
            ))
    ));
?>
```

**Comment by m1r0** [comment]
A better solution is needed. Maybe instead of saving empty values for the fields, each complex group should save an additional meta that flags the group as added.

**Comment by georgknabl** [comment]
I'd keep the number of additional meta fields as low as possible to reduce the number of SQL-queries on saving and retrieving which causes scalability issues in the long run. ACF has that problem and I suggest not going down this road if it can be avoided.
The obvious approach might be using "null" on a sub-item meaning "no contents" but still states that it exists. Other meta data (if needed) can still be added when the whole complex field is serialized in the first place.

**Comment by pkostadinov-2create** [comment]
I have experienced the same issue.

My current workaround is an extended field that clones the HTML field, and also allows you to use `set_default_value`, causing the Empty groups to be saved. For better User experience, you can use the `set_html` method to explain to the end-user why there are no settings to that group, and potentially add a link to a CPT edit screen.

https://github.com/pkostadinov-2create/carbon-field-hidden/tree/namespaced  (namespaced branch)

Use case:
```
<?php
use Carbon_Fields\Container;
use Carbon_Fields\Field;

Container::make('post_meta', 'Empty Fields Test')
	->show_on_post_type('page')
	->add_fields(array(
		Field::make('complex', 'fields', 'Fields')
			->add_fields('module', 'Empty Field', array(
				Field::make('hidden', 'any_label', 'any_label')
					->set_default_value('any_value'),
					->set_html(
						sprintf(
							__('This module will display content from <a href="%s">CPT</a>', 'crb'),
							admin_url('edit.php?post_type=module')
						)
					)
			))
	));
?>
```

However this does not solve the extra query.

**Comment by timiwahalahti** [comment]
Oh well, this is something that drives me nuts.

I have complex field containing 23 fields which are shown with conditional logic. After this change, every field is saved to database even if it does not match to conditional logic. This is just unnecessary and fills up the database with useless rows.

For example, I have that one complex field with 12 repeats containing 23 fields, from where is 1-10 shown after conditional logic based on one field. I counted that there's right now **272** rows in database when only **57** of those contains actual data and will be used.

There's should really be an option or at least filter to prevent saving empty fields.

**Comment by atanas-angelov-dev** [comment]
@timiwahalahti,

Our latest tests show that this is no longer the case. Can you please check if the issue persists and send us your field definitions if it does, so that we can investigate.

**Comment by timiwahalahti** [comment]
Grabbed the latest code from repo (previously was from wpackagist) and empty rows as described above seems continue to happen. Basically the problem is commit c69bdebdd57cf1e73871dba4e94a513eb2e216d7 which is still in codebase. Function `array_filter_remove_empty_values` should be added back with option to execute it.

Field definitions can be found from [this gist](https://gist.github.com/timiwahalahti/cdc31270f727ba6509b203dae2f64861).

**Comment by atanas-angelov-dev** [comment]
1.6 will be a maintenance release which aims at stability and full backwards compatibility so we will have to close feature pull requests aiming at 1.x.

In 2.0 complex fields will always save their entries, even if they have falsy/no fields.
In addition, there are 2 filters allowing you to control whether old values should be deleted and whether new ones should be saved (e.g. you can add a filter which checks if the value is empty and prevent the field from saving it).
