### ISSUE TITLE
Missing preview image

### ISSUE THREAD

**Issue by kazztor-** [htmlburger/carbon-fields#635]
## Version

  - Carbon Fields: 3.0.1
  - WordPress:  5.0.2 
  - PHP: 7.2
 - Plugin Quickstart / Without Composer

## Expected Behavior
See image preview in back end

## Actual Behavior
return empty holder in the back end, but shows the image in the front end

## Container definition
```php
Container::make( 'post_meta', 'slider', __( 'Slider' ) )
  ->where( 'post_type', '=', 'post' )
  ->add_fields( array (
    Field::make( 'complex', 'slide', __( 'Slide' ) )
      ->set_layout( 'tabbed-horizontal' )
      ->add_fields( array( 
        Field::make( 'image', 'slide_image', __( 'Image' ) ),
        Field::make( 'text', 'slide_text', __( 'Text' ) ),
        Field::make( 'text', 'slide_target', __( 'Target' ) ),
        Field::make( 'checkbox', 'slide_new_window', __( 'Open in a new window' ) )
          ->set_option_value( 'yes' )
      )),
  ));
```

## Steps to Reproduce the Problem

  1. create new post
  2. select and image from media gallery
  3. update post

![cf_301](https://user-images.githubusercontent.com/6578687/50865567-3f42fe80-1374-11e9-8772-2cdb2c52371a.jpg)
Carbon Fields 3.01

```html
<div class="cf-field cf-image">
    <div class="cf-field__head">
        <label class="cf-field__label" for="cf-ohXpzOkE8BvYXpMql2URC">Image</label>
    </div>
    <div class="cf-field__body">
        <div class="cf-file__inner">
            <input type="hidden" name="carbon_fields_compact_input[_slide][0][_slide_image]" readonly="" value="10">
            <button type="button" class="button cf-file__browse">Select Image</button>
        </div>
    </div>
</div>
```

## Comments
The problem occurs in both IONOS (1&1) and godaddy hosting.

Works correctly in Carbon Fields 2.2
![cf_22](https://user-images.githubusercontent.com/6578687/50865565-3c480e00-1374-11e9-9cdc-e5f80dab44e8.jpg)

**Comment by KevinSupertramp** [comment]
Hi,

I have the same here using theme options.

Kind regards,

**Comment by KevinSupertramp** [comment]
Hi there,

It actually works for me now, as long as I don't use a .SVG. When I select a SVG the preview image is missing.

Best,

**Comment by brnteka** [comment]
I was able to make SVG visible in preview by using "SVG Support" plugin and setting field to "file" type

**Comment by bsdsouzagit** [comment]
Hi,

I have the same problem after active preview block and return edition mode again.

**Comment by sanjayatony** [comment]
is this already solved?
using version 3.1.1 the preview is missing. the image is jpg btw

**Comment by pjehan** [comment]
I seem to be facing the  same issue with a .jpg image.
Image is saved in database but not showing up as a thumbnail in the admin interface.

**Comment by RocKhalil** [comment]
The issue is that the API calling `wp-json/carbon-fields/v1/attachment/?type=id&value=104` for example is returning `500` but also returning the data.
I'm not even sure why it's returning 500

**Comment by RocKhalil** [comment]
Turned out my issue was with Caching.
I'm using OpenLiteSpeed and had the `Cache Rest API` on.
Try disabling it and it should work fine :-)

**Comment by ChrisButterworth** [comment]
I'm having this issue too - checked that it isn't caching, i'm using a SVG using Safe SVG to allow it.

I don't have cache running and have enabled script debug but no success

**Comment by pjehan** [comment]
I realized I only get this error if I am not using URL rewriting...
So this request returns 404 : ```http://localhost:3000/index.php?rest_route=/carbon-fields/v1/attachment/?type=id&value=8```
But this one returns 200 : ```http://localhost:3000/wp-json/carbon-fields/v1/attachment/?type=id&value=8```

I've checked in the source code and this error seems to come from the REST API used in the file ```/packages/core/fields/file/index.js``` on line 34. However, there is a TODO above so I guess this issue might be resolved when the refactoring will be done :smile:
```php
// TODO: Refactor this to use `@wordpress/api-fetch` package.
```

**Comment by jorostoyanov** [comment]
This has been fixed in v3.2.0

Please update :-)

**Comment by phamgiahung1368** [comment]
@jorostoyanov  this issue still persist in carbon field 3.3.0

**Comment by yunusga** [comment]
@jorostoyanov and 3.3.2

**Comment by fernandopro** [comment]
Same problem in version 3.3.4.
I am using Plugin Quick start version
