### ISSUE TITLE
image field mime type set svg

### ISSUE THREAD

**Issue by flexo911** [htmlburger/carbon-fields#660]
## Version

  - Carbon Fields: 3.0.2
  - WordPress: 5.0.3
  - PHP: 7.2

## Expected Behavior
I use svg as image(only icons)
After choose image on media, background set as chosen image. After press Update background is missed

## Container definition
```php
Field::make( 'image', 'features_image_main', 'Features photo' )
                    ->set_width( 50 )
                    ->set_value_type( 'url' ),
```

## Comments

After updating the page, all the svg pictures disappear, but they become a background when loading. Maybe there is a way around this.
Please help this.

**Comment by jorostoyanov** [comment]
Fixed in https://github.com/htmlburger/carbon-fields/commit/4aac21d3c3cc537e2c02c5f3a8c094a6567d3dac

**Comment by AlexL-JWA** [comment]
Same error to theme option `$options_container = Container::make(
			'theme_options',
			__( 'General Options', 'ten' )
		)->add_fields(
			[
				Field::make( 'image', 'ten_logo', __( 'Logo', 'ten' ) )
					->set_help_text( __( 'Set a Logo Image', 'ten' ) )
					->set_width( 50 )
					->set_value_type( 'url' ),

				Field::make( 'image', 'ten_logo_white', __( 'Logo White' ) )
					->set_help_text( __( 'Set a White Logo Image', 'ten' ) )
					->set_width( 50 )
					->set_value_type( 'url' ),

				Field::make( 'text', 'ten_google_front', __( 'Google Font' ) )
					->set_attribute( 'placeholder', 'url google front' )
					->set_default_value( 'https://fonts.googleapis.com/css2?family=Chivo:wght@400;700&amp;family=Poppins:wght@400;700&amp;family=Roboto:wght@400;700&amp;display=swap' ),

				Field::make( 'footer_scripts', 'ten_footer_scripts', __( 'Footer Analytics Scripts' ) ),

			]
		);`

**Comment by avblink** [comment]
I still experience the same issue.

v3.6.5

![image](https://github.com/user-attachments/assets/f2e8ee5b-758d-4270-ad99-a05f07ed1860)
