### ISSUE TITLE
carbon_fields_gravity_form_options doesn't seem to work

### ISSUE THREAD

**Issue by duncanarrow** [htmlburger/carbon-fields#977]
## Version

  - Carbon Fields: 3.2.2
  - WordPress: 5.7
  - PHP: 7.2

## Expected Behavior
To be able to update the default entry in a gravity_form field

## Actual Behavior
Creating the field works fine when adding this to functions.php. And it shows the correct list of Gravity Forms. But `carbon_fields_gravity_form_options` doesn't seem to fire so I can't overwrite the default message in `$options`. 

Any ideas?

## Container definition

```
	// Show all Gravity Forms
	add_action( 'carbon_fields_register_fields', 'show_gravity_form_field' );
	function show_gravity_form_field() {
		Container::make( 'post_meta', __( 'Show all Gravity Forms' ) )
			->where( 'post_type', '=', 'post' )
			->add_fields( array(
				 Field::make( 'gravity_form', 'crb_gravity_form', __( 'Select a Form') )
				 //->set_default_value( '0' ),
		));
	}
	
	// Change the default select option - doesn't work!
	add_filter( 'carbon_fields_gravity_form_options', 'crb_my_gravity_form_options' );
	function crb_my_gravity_form_options( $options ) {
	    $options[''] = 'Please select a form...';
	    return $options;
	}
```

## Steps to Reproduce the Problem

  1. Copy the above code to functions.php
  2. You'll see the problem when you go to the post backend

**Comment by jorostoyanov** [comment]
Fixed in development branch :)

Thanks for pointing this out, @duncanarrow

**Comment by duncanarrow** [comment]
@jorostoyanov Brilliant thanks! I've applied that fix to my install and it does now work, although it still shows `No form` as the first item in the select menu and my override as the very last option. I then have to use `set_default_value` to use the value that I set in `carbon_fields_gravity_form_options`.

Is this expected and intended behaviour? I'm not sure. I'd have thought that the override in `carbon_fields_gravity_form_options` should become the first item in the list and maybe the default option of `No form` should be removed completely?

```
	// Show all Gravity Forms
	add_action( 'carbon_fields_register_fields', 'show_gravity_form_field' );
	function show_gravity_form_field() {
		Container::make( 'post_meta', __( 'Show all Gravity Forms' ) )
			->where( 'post_type', '=', 'post' )
			->add_fields( array(
				 Field::make( 'gravity_form', 'crb_gravity_form', __( 'Select a Form') )
				 ->set_default_value( '4' ),
		));
	}
	
	add_filter( 'carbon_fields_gravity_form_options', 'crb_my_gravity_form_options' );
	function crb_my_gravity_form_options( $options ) {
	    $options[] = __( 'Please select a form...' );
	    return $options;
	}
```

**Comment by duncanarrow** [comment]
@jorostoyanov in fact something like this works for me as it also removes the default `No form` option as well. I can also then remove the `set_default_value` value in `carbon_fields_register_fields`.

Does that have any other implications though?

```
	add_filter( 'carbon_fields_gravity_form_options', 'crb_my_gravity_form_options' );
	function crb_my_gravity_form_options( $options ) {
	    $override = array('' => 'Please select a form...');
	    $options = $override + $options;
	    return $options;
	}
```

**Comment by jorostoyanov** [comment]
Looks good to me. Use it as shown 😉

Cheers!
